---
version: 2.1

parameters:
  go-version:
    type: string
    default: "1.14.6"
  workspace-dir:
    type: string
    default: "/home/circleci"

commands:
  setup:
    description: "checkout, restore cache, init submodules and build deps"
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-pkg-cache-{{ checksum "go.sum" }}-{{ .Environment.GOVERSION }}'
      - run: sudo apt-get update
      - run: sudo apt-get install ocl-icd-opencl-dev
      - run: git submodule sync
      - run: git submodule update --init
      - run: cd gen/extern/filecoin-ffi && make

executors:
  golang:
    docker:
      - image: circleci/golang:1.14.6
    working_directory: << pipeline.parameters.workspace-dir >>/project
    environment:
      GOVERSION: << pipeline.parameters.go-version >>

workflows:
  version: 2
  main:
    jobs:
      - build-and-generate

jobs:
  build-and-generate:
    executor: golang
    steps:
      - setup
      - run:
          name: "build builder api"
          command: pushd gen/builders && go build .
      - run:
          name: "generate vectors"
          command: make gen
      - run:
          name: "validate vectors against JSON Schema"
          command: make validate
      - save_cache:
          key: 'v1-pkg-cache-{{ checksum "go.sum" }}-{{ .Environment.GOVERSION }}'
          paths:
            - << pipeline.parameters.workspace-dir >>/go/<< pipeline.parameters.go-version >>/pkg/mod
